# Generated by Django 5.0.1 on 2024-03-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyprofile_fee_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyprofile',
            old_name='propertyImage',
            new_name='image',
        ),
    ]
